name: NMGKJ API Daily Check

on:
  schedule:
    - cron: '0 18 * * *'  # UTC 18:00 = 北京时间次日02:00
    - cron: '0 19 * * *'  # UTC 18:00 = 北京时间次日03:00
  workflow_dispatch:  # 允许手动触发

jobs:
  api-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 任务超时时间
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    # 直接使用系统自带的Node.js，完全跳过setup-node
    - name: 执行接口调用
      run: |
        # 显示Node.js版本信息
        echo "使用系统预装的Node.js版本: $(node --version)"
        
        # 执行监控脚本
        node api-caller.js
        
        # 检查执行结果
        if [ $? -ne 0 ]; then
          echo "::error::接口调用失败"
          exit 1
        else
          echo "✅ 接口调用成功"
        fi
