name: NMGKJ API Daily Check

on:
  schedule:
    - cron: '0 18 * * *'  # UTC 18:00 = 北京时间次日02:00
  workflow_dispatch:  # 允许手动触发

jobs:
  api-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 任务超时时间
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    # 仅设置Node.js环境，不尝试缓存依赖
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'false'  # 明确禁用缓存功能
        
    - name: 执行接口调用
      run: node api-caller.js
      
    # 验证步骤（可选，因为脚本内已有验证）
    - name: 验证结果
      run: |
        if ! node api-caller.js; then
          echo "::error::接口检查失败"
          exit 1
        else
          echo "✅ 接口检查成功"
        fi
