name: NMGKJ API Daily Check

on:
  schedule:
    - cron: '0 18 * * *'  # UTC 18:00 = 北京时间次日02:00
  workflow_dispatch:

jobs:
  api-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    # 使用系统自带Node.js
    - name: 检查Node.js版本
      run: |
        echo "Node.js版本: $(node --version)"
        echo "npm版本: $(npm --version)"
      
    # 直接安装所需依赖
    - name: 安装依赖
      run: |
        npm install axios --global --no-package-lock  # 全局安装避免锁定文件问题
        echo "依赖安装完成"
      
    - name: 执行接口调用
      run: node api-caller.js
      
    # 简化的响应验证
    - name: 验证响应
      run: |
        # 使用curl进行验证
        if ! curl -s -o /dev/null -w "%{http_code}" http://training.nmgkj.edufe.cn/JXJY/nmgkj/api/nmgCallBackTest | grep -q 200; then
          echo "::error::接口响应状态异常"
          exit 1
        else
          echo "✅ 接口响应验证通过"
        fi
